#pragma once
#include <stdio.h>

void reverser();
void Check_sys();
void FFO();
void SumOfSn();
void PointerPrintArray();
void NarcissisticNumber();
void PrintDiamond();
void SodaProblem();
void OddEvenSort();
void PascalTriangle();
void Killer();
void DivingProblem();
void QsortFunIsUsed(); 
void YanghuiTriangle();
void YanghuiTriangle_Recursion(); 
void DiveRanking(); 
void FindsNumberYoungTableau();