#pragma once
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <errno.h>
#include <ctype.h>

void reverser();
void Check_sys();
void FFO();
void SumOfSn();
void PointerPrintArray();
void NarcissisticNumber();
void PrintDiamond();
void SodaProblem();
void OddEvenSort();
void PascalTriangle();
void Killer();
void DivingProblem();
void QsortFunIsUsed(); 
void YanghuiTriangle();
void YanghuiTriangle_Recursion(); 
void DiveRanking(); 
void FindsNumberYoungTableau(); 
void StrLeftRotation(); 
void myStrlen();
void myStrcpy();
void myStrcat();
void myStrcmp();
void myStrncpy();
void myStrstr();
void myStrtok();
void strerror_test(); 
void perror_test();
void myMemoryOperationFunctionCases();
void CustomMemoryAlignment();